const $=id=>document.getElementById(id);
const S={ws:null,symbol:null,prices:[],times:[],candles:[],voice:true,signal:null,lastLogged:'',timeframe:60,req:100,historyReq:null,historyStatus:'SIN CARGAR',historyTf:null,historySymbol:null,chart:null,candleSeries:null,resizeObs:null};
const els={symbol:$('symbol'),connect:$('connect'),conn:$('conn'),price:$('price'),ticks:$('ticks'),direction:$('direction'),confidence:$('confidence'),phase:$('phase'),reason:$('reason'),alert:$('alertLevel'),entry:$('entryLevel'),exit:$('exitLevel'),spike:$('spikeRisk'),ind:$('indicators'),history:$('history')};
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function syncUI(){const s=S.signal||{};setText('radarDir',s.dir||'ESPERANDO');setText('graphDir',s.dir||'ESPERANDO');setText('graphConf',(s.conf||0)+'%');setText('graphPhase',s.phase||'ESPERANDO');setText('graphReason',els.reason.textContent);setText('graphTarget',s.exit?.toFixed(5)||'—');setText('graphSpike',(s.spikeRisk||0)+'%');setText('graphPrice',els.price.textContent);setText('infoPrice',els.price.textContent);setText('infoTicks',els.ticks.textContent);setText('infoDir',s.dir||'NEUTRAL');setText('infoAlert',s.alert?.toFixed(5)||'—');setText('infoEntry',s.entry?.toFixed(5)||'—');setText('infoExit',s.exit?.toFixed(5)||'—');setText('graphConn',S.ws?.readyState===1?'● DERIV EN VIVO':'● DERIV')}
function speak(t){if(!S.voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-SV';u.rate=.95;speechSynthesis.speak(u)}
function send(o){if(S.ws?.readyState===1)S.ws.send(JSON.stringify(o))}
function connect(){if(S.ws)S.ws.close();S.ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');els.conn.textContent='CONECTANDO…';S.ws.onopen=()=>{els.conn.textContent='DERIV CONECTADO';els.conn.className='pill on';send({active_symbols:'brief',req_id:1});speak('Radar Sintético MR conectado a Deriv')};S.ws.onclose=e=>{els.conn.textContent='DERIV DESCONECTADO';els.conn.className='pill off';els.reason.textContent=`Conexión cerrada${e.code?` (código ${e.code})`:''}. Pulse Conectar Deriv para reintentar.`};S.ws.onerror=()=>{els.conn.textContent='ERROR DERIV';els.conn.className='pill off';els.reason.textContent='No se pudo abrir el canal público de Deriv.'};S.ws.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch{return}handle(d)}}
function handle(d){
 if(d.error){if(d.req_id===S.historyReq){showChartError('Deriv rechazó el histórico OHLC: '+d.error.message);S.historyStatus='ERROR OHLC (HISTÓRICO)'}else els.reason.textContent=d.error.message;updateBadge();return}
 if(d.msg_type==='active_symbols'){const list=(d.active_symbols||[]).filter(x=>/boom|crash/i.test(x.underlying_symbol_name||x.display_name||''));els.symbol.innerHTML='';list.forEach(x=>{const o=document.createElement('option');o.value=x.underlying_symbol||x.symbol;o.textContent=x.underlying_symbol_name||x.display_name||o.value;els.symbol.appendChild(o)});$('graphSymbol').innerHTML=els.symbol.innerHTML;if(list.length){S.symbol=els.symbol.value;$('graphSymbol').value=S.symbol;subscribe()}}
 if(d.msg_type==='history'&&d.history){S.prices=(d.history.prices||[]).map(Number);S.times=(d.history.times||[]).map(Number);analyze()}
 if(d.msg_type==='candles'&&Array.isArray(d.candles)&&d.req_id===S.historyReq&&S.historySymbol===S.symbol&&S.historyTf===S.timeframe)acceptCandles(d.candles)
 if(d.msg_type==='tick'){const q=Number(d.tick.quote),ep=Number(d.tick.epoch);if(!Number.isFinite(q)||!Number.isFinite(ep))return;S.prices.push(q);S.times.push(ep);if(S.prices.length>600){S.prices.shift();S.times.shift()}updateLiveCandle(q,ep);analyze()}
}
function normalizeCandles(list){const map=new Map();for(const c of list||[]){const x={time:Number(c.epoch),open:Number(c.open),high:Number(c.high),low:Number(c.low),close:Number(c.close)};if(![x.time,x.open,x.high,x.low,x.close].every(Number.isFinite))continue;if(x.high<Math.max(x.open,x.close)||x.low>Math.min(x.open,x.close)||x.high<x.low)continue;map.set(x.time,x)}return [...map.values()].sort((a,b)=>a.time-b.time).slice(-300)}
function analyzeCandleDiagnostics(raw,cs,tf){
 const rawN=Array.isArray(raw)?raw.length:0,n=cs.length;
 const diffs=[];let nonPositive=0,duplicates=0,exact=0,off=0,minDiff=null,maxDiff=null;
 for(let i=1;i<n;i++){const d=cs[i].time-cs[i-1].time;diffs.push(d);if(d<=0)nonPositive++;if(d===0)duplicates++;if(d===tf)exact++;else off++;if(d>0){minDiff=minDiff===null?d:Math.min(minDiff,d);maxDiff=maxDiff===null?d:Math.max(maxDiff,d)}}
 const freq={};for(const d of diffs)freq[d]=(freq[d]||0)+1;
 const common=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([d,c])=>`${d}s × ${c}`).join(' · ')||'—';
 const first=cs[0]||null,last=cs[n-1]||null;
 let reason='OK';
 if(n<10)reason=`RECHAZO: solo ${n} velas OHLC válidas`;
 else if(duplicates)reason=`RECHAZO: ${duplicates} timestamps duplicados`;
 else if(nonPositive)reason=`RECHAZO: ${nonPositive} intervalos no crecientes`;
 else if(off>Math.max(2,Math.floor(n*.05)))reason=`RECHAZO ACTUAL: ${off}/${Math.max(0,n-1)} intervalos no son exactamente ${tf}s`;
 return {rawN,n,tf,diffs,nonPositive,duplicates,exact,off,minDiff,maxDiff,common,first,last,reason};
}
function renderOhlcDiagnostic(raw,cs,diag){
 const box=$('ohlcDiagnostic');if(!box)return;
 const rows=[];const picks=[...cs.slice(0,5),...cs.slice(-5)];
 for(const c of picks){const dt=new Date(c.time*1000);rows.push(`<tr><td>${dt.toLocaleString()}</td><td>${c.time}</td><td>${c.open}</td><td>${c.high}</td><td>${c.low}</td><td>${c.close}</td></tr>`)}
 const first=diag.first?`${diag.first.time} · ${new Date(diag.first.time*1000).toLocaleString()}`:'—';
 const last=diag.last?`${diag.last.time} · ${new Date(diag.last.time*1000).toLocaleString()}`:'—';
 box.innerHTML=`<div class="diag-title">V1.5.3 · DIAGNÓSTICO ESTRICTO OHLC</div>
 <div class="diag-grid">
  <div>RECIBIDAS<b>${diag.rawN}</b></div><div>VÁLIDAS<b>${diag.n}</b></div><div>TF ESPERADO<b>${diag.tf}s</b></div><div>INTERVALOS EXACTOS<b>${diag.exact}</b></div>
  <div>DIFERENCIAS<b>${diag.off}</b></div><div>MÍN / MÁX<b>${diag.minDiff??'—'}s / ${diag.maxDiff??'—'}s</b></div><div>DUPLICADOS<b>${diag.duplicates}</b></div><div>ORDEN INVÁLIDO<b>${diag.nonPositive}</b></div>
 </div>
 <div class="diag-reason ${diag.reason==='OK'?'diag-ok':'diag-bad'}"><b>MOTIVO:</b> ${diag.reason}</div>
 <div class="diag-line"><b>INTERVALOS MÁS FRECUENTES:</b> ${diag.common}</div>
 <div class="diag-line"><b>PRIMER EPOCH:</b> ${first}</div><div class="diag-line"><b>ÚLTIMO EPOCH:</b> ${last}</div>
 <table class="diag-table"><thead><tr><th>Hora</th><th>epoch</th><th>open</th><th>high</th><th>low</th><th>close</th></tr></thead><tbody>${rows.join('')}</tbody></table>`;
}
function validateDirectCandles(cs,tf,diag){if(cs.length<10)return {ok:false,msg:`Solo ${cs.length} velas OHLC válidas`};if(diag.duplicates)return {ok:false,msg:`${diag.duplicates} timestamps duplicados`};if(diag.nonPositive)return {ok:false,msg:`${diag.nonPositive} intervalos no crecientes`};if(diag.off>Math.max(2,Math.floor(cs.length*.05)))return {ok:false,msg:`${diag.off} de ${cs.length-1} intervalos difieren de ${tf}s (mín ${diag.minDiff??'—'}s, máx ${diag.maxDiff??'—'}s)`};return {ok:true,msg:'OHLC DIRECTO VALIDADO'}}
function acceptCandles(list){const cs=normalizeCandles(list);const tf=S.historyTf||S.timeframe;const diag=analyzeCandleDiagnostics(list,cs,tf);renderOhlcDiagnostic(list,cs,diag);console.log('OHLC DIAG',diag);console.table(cs.slice(0,5));console.table(cs.slice(-5));const v=validateDirectCandles(cs,tf,diag);if(!v.ok){S.candles=[];S.historyStatus='HISTÓRICO INVÁLIDO · VER DIAGNÓSTICO';showChartError(`${v.msg}. Revise el panel DIAGNÓSTICO ESTRICTO OHLC.`);updateBadge();return}hideChartError();S.candles=cs;S.historyStatus=`${cs.length} OHLC DIRECTO · VALIDADO`;renderAll(true);updateBadge()}
function requestCandles(){if(!S.symbol)return;S.candles=[];S.historyReq=++S.req;S.historyTf=S.timeframe;S.historySymbol=S.symbol;S.historyStatus='SOLICITANDO OHLC DIRECTO';hideChartError();updateBadge();const box=$('ohlcDiagnostic');if(box)box.innerHTML=`<div class="diag-title">V1.5.3 · DIAGNÓSTICO ESTRICTO OHLC</div><div class="diag-line">Solicitando 200 velas · símbolo ${S.historySymbol} · granularidad ${S.historyTf}s…</div>`;const req={ticks_history:S.historySymbol,count:200,end:'latest',style:'candles',granularity:S.historyTf,req_id:S.historyReq};console.log('OHLC REQUEST',req);send(req);const myReq=S.historyReq;setTimeout(()=>{if(myReq===S.historyReq&&!S.candles.length&&S.historyStatus==='SOLICITANDO OHLC DIRECTO')showChartError('Sin respuesta OHLC directa de Deriv. Revise conexión y solicitud.')},7000)}
function subscribe(){if(!S.symbol)return;send({forget_all:'ticks'});S.prices=[];S.times=[];S.signal=null;send({ticks_history:S.symbol,count:300,end:'latest',style:'ticks',req_id:2});requestCandles();send({ticks:S.symbol,subscribe:1,req_id:3});els.reason.textContent='Recopilando datos del mercado…'}
function updateLiveCandle(price,epoch){if(!S.candles.length)return;const bucket=Math.floor(epoch/S.timeframe)*S.timeframe;let c=S.candles[S.candles.length-1];if(bucket<c.time)return;if(bucket>c.time){c={time:bucket,open:c.close,high:Math.max(c.close,price),low:Math.min(c.close,price),close:price};S.candles.push(c);if(S.candles.length>300)S.candles.shift()}else{c.high=Math.max(c.high,price);c.low=Math.min(c.low,price);c.close=price}S.candleSeries?.update(c);updateEmaLive();updateOHLC(c);updateBadge()}
function ensureChart(){if(S.chart)return true;if(!window.LightweightCharts){showChartError('No cargó el motor financiero Lightweight Charts. Revise la conexión a Internet.');return false}const host=$('lwChart');const dark=!document.body.classList.contains('light');S.chart=LightweightCharts.createChart(host,{autoSize:true,layout:{background:{type:'solid',color:dark?'#07111d':'#f7fbff'},textColor:dark?'#9fb4c8':'#52677b'},grid:{vertLines:{color:dark?'#173049':'#dce8f1'},horzLines:{color:dark?'#173049':'#dce8f1'}},rightPriceScale:{borderColor:dark?'#294157':'#cadbe7',autoScale:true,scaleMargins:{top:.08,bottom:.08}},timeScale:{borderColor:dark?'#294157':'#cadbe7',timeVisible:true,secondsVisible:false,rightOffset:5,barSpacing:10,minBarSpacing:4,fixLeftEdge:false,fixRightEdge:false},crosshair:{mode:0},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{axisPressedMouseMove:true,mouseWheel:true,pinch:true}});S.candleSeries=S.chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:'#08a85d',downColor:'#f43d4d',borderUpColor:'#08a85d',borderDownColor:'#f43d4d',wickUpColor:'#08a85d',wickDownColor:'#f43d4d',priceLineVisible:true,lastValueVisible:true});S.chart.subscribeCrosshairMove(p=>{if(!p.time)return;const d=p.seriesData.get(S.candleSeries);if(d)updateOHLC(d)});return true}
function showRecentCandles(count=70){if(!S.chart||!S.candles.length)return;const n=S.candles.length;const visible=Math.min(count,n);S.chart.timeScale().setVisibleLogicalRange({from:n-visible-2,to:n+4})}
function renderAll(fit=false){if(!ensureChart()||!S.candles.length)return;S.candleSeries.setData(S.candles);if(fit)showRecentCandles(70);updateOHLC(S.candles[S.candles.length-1])}
function updateEmaLive(){}
function updateOHLC(c){const e=document.querySelector('.ohlc');if(!e||!c)return;e.innerHTML=`O ${Number(c.open).toFixed(5)} &nbsp; H ${Number(c.high).toFixed(5)} &nbsp; L ${Number(c.low).toFixed(5)} &nbsp; C ${Number(c.close).toFixed(5)} <span>· OHLC Deriv</span>`}
function updateBadge(){const tf=document.querySelector('.tf.active')?.textContent||'1m';setText('chartBadge',`${tf} · ${S.candles.length} velas · ${S.historyStatus}`)}
function showChartError(t){const e=$('chartError');if(e){e.textContent=t;e.hidden=false}updateBadge()}
function hideChartError(){const e=$('chartError');if(e)e.hidden=true}
function applyChartTheme(){if(!S.chart)return;const dark=!document.body.classList.contains('light');S.chart.applyOptions({layout:{background:{type:'solid',color:dark?'#07111d':'#f7fbff'},textColor:dark?'#9fb4c8':'#52677b'},grid:{vertLines:{color:dark?'#173049':'#dce8f1'},horzLines:{color:dark?'#173049':'#dce8f1'}}})}
const avg=a=>a.reduce((s,v)=>s+v,0)/(a.length||1),sd=a=>{const m=avg(a);return Math.sqrt(avg(a.map(v=>(v-m)**2)))};function ema(a,n){if(!a.length)return 0;let k=2/(n+1),v=a[0];for(const x of a.slice(1))v=x*k+v*(1-k);return v}
function analyze(){const p=S.prices,n=p.length;els.ticks.textContent=n;if(n<40){syncUI();return}const cur=p[n-1],r=p.slice(-40),fast=ema(r.slice(-15),8),slow=ema(r,21),mom=cur-p[n-11],vol=sd(r.slice(-25)),unit=vol||Math.abs(cur)*.00001||1,score=(fast-slow)/unit*.22+mom/unit*.12,conf=Math.min(92,Math.round(50+Math.abs(score)*18)),dir=score>.35?'ALZA ↑':score<-.35?'BAJA ↓':'NEUTRAL';const deltas=r.slice(1).map((v,i)=>v-r[i]),largest=Math.max(...deltas.map(Math.abs)),spikeRisk=Math.min(95,Math.round(20+Math.max(0,largest/unit-1)*10+Math.min(35,Math.abs(score)*8)));let phase='ESPERAR',reason='Sin confirmación suficiente.',alert=null,entry=null,exit=null;if(dir!=='NEUTRAL'&&conf>=62){phase='🟡 ALERTA';alert=cur;reason='Dirección emergente detectada. Vigilando confirmación.'}if(dir!=='NEUTRAL'&&conf>=72){phase='🟢 ENTRADA';entry=cur;alert=S.signal?.alert??cur;exit=cur+(dir.startsWith('ALZA')?1:-1)*unit*2.2;reason='Momentum y estructura confirman la dirección.'}S.signal={dir,conf,phase,alert,entry,exit,spikeRisk};els.price.textContent=cur.toFixed(5);els.direction.textContent=dir;els.confidence.textContent=conf+'%';els.phase.textContent=phase;els.reason.textContent=reason;els.alert.textContent=alert?.toFixed(5)||'—';els.entry.textContent=entry?.toFixed(5)||'—';els.exit.textContent=exit?.toFixed(5)||'—';els.spike.textContent=spikeRisk+'%';els.ind.innerHTML=`Momentum: ${mom.toFixed(5)}<br>Volatilidad: ${vol.toFixed(5)}<br>EMA rápida/lenta: ${fast.toFixed(5)} / ${slow.toFixed(5)}`;syncUI();const key=phase+dir;if((phase.includes('ALERTA')||phase.includes('ENTRADA'))&&key!==S.lastLogged){S.lastLogged=key;logSignal();speak(`${phase.includes('ENTRADA')?'Entrada confirmada':'Alerta'} ${dir.startsWith('ALZA')?'al alza':'a la baja'}`)}}
function logSignal(){const s=S.signal,tr=document.createElement('tr');tr.innerHTML=`<td>${new Date().toLocaleTimeString()}</td><td>${els.symbol.options[els.symbol.selectedIndex]?.text||S.symbol}</td><td>${s.dir}</td><td>${s.phase}</td><td>${s.conf}%</td><td>${s.alert?.toFixed(5)||'—'}</td><td>${s.entry?.toFixed(5)||'—'}</td><td>${s.exit?.toFixed(5)||'—'}</td>`;els.history.prepend(tr);while(els.history.children.length>30)els.history.lastChild.remove()}
function showView(name){document.body.classList.toggle('graph-mode',name==='graph');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$(name+'View').classList.add('active');if(name==='graph')setTimeout(()=>{ensureChart();renderAll(false);showRecentCandles(70)},80)}
els.connect.onclick=connect;els.symbol.onchange=()=>{S.symbol=els.symbol.value;$('graphSymbol').value=S.symbol;S.lastLogged='';subscribe()};$('graphSymbol').onchange=()=>{els.symbol.value=$('graphSymbol').value;S.symbol=els.symbol.value;subscribe()};$('voice').onclick=()=>{S.voice=!S.voice;$('voice').textContent=`🔊 Voz: ${S.voice?'ON':'OFF'}`};$('clear').onclick=()=>{S.signal=null;S.lastLogged='';syncUI()};document.querySelectorAll('.tf').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tf').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.timeframe=Number(b.dataset.sec);requestCandles()});document.querySelectorAll('.nav').forEach(b=>{if(b.dataset.view)b.onclick=()=>showView(b.dataset.view)});$('openGraph').onclick=()=>showView('graph');$('backRadar').onclick=()=>showView('radar');$('theme').onclick=()=>{document.body.classList.toggle('light');$('theme').textContent=document.body.classList.contains('light')?'🌙 Oscuro':'☀️ Claro';applyChartTheme()};$('graphTheme').onclick=()=>$('theme').click();$('togglePanel').onclick=()=>document.querySelector('.terminal-body')?.classList.toggle('panel-open');$('closePanel').onclick=()=>document.querySelector('.terminal-body')?.classList.remove('panel-open');$('panelBackdrop').onclick=()=>document.querySelector('.terminal-body')?.classList.remove('panel-open');$('zoomIn').onclick=()=>{if(!S.chart)return;const ts=S.chart.timeScale(),r=ts.getVisibleLogicalRange();if(r)ts.setVisibleLogicalRange({from:r.from+5,to:r.to-5})};$('zoomOut').onclick=()=>{if(!S.chart)return;const ts=S.chart.timeScale(),r=ts.getVisibleLogicalRange();if(r)ts.setVisibleLogicalRange({from:r.from-8,to:r.to+8})};$('resetChart').onclick=()=>showRecentCandles(70);window.addEventListener('resize',()=>setTimeout(()=>showRecentCandles(70),80));
