const $=id=>document.getElementById(id); const S={ws:null,symbol:null,prices:[],times:[],voice:true,signal:null,lastLogged:''};
const els={symbol:$('symbol'),connect:$('connect'),conn:$('conn'),price:$('price'),ticks:$('ticks'),direction:$('direction'),confidence:$('confidence'),phase:$('phase'),reason:$('reason'),alert:$('alertLevel'),entry:$('entryLevel'),exit:$('exitLevel'),spike:$('spikeRisk'),ind:$('indicators'),history:$('history'),chart:$('chart')};
function speak(t){if(!S.voice||!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-SV';u.rate=.95;speechSynthesis.speak(u)}
function send(o){if(S.ws?.readyState===1)S.ws.send(JSON.stringify(o))}
function connect(){if(S.ws)S.ws.close();S.ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');els.conn.textContent='CONECTANDO…';S.ws.onopen=()=>{els.conn.textContent='DERIV CONECTADO';els.conn.className='pill on';send({active_symbols:'brief',req_id:1});speak('Radar Sintético MR conectado a Deriv')};S.ws.onclose=e=>{els.conn.textContent='DERIV DESCONECTADO';els.conn.className='pill off';els.reason.textContent=`Conexión cerrada${e.code?` (código ${e.code})`:''}. Pulse Conectar Deriv para reintentar.`};S.ws.onerror=()=>{els.conn.textContent='ERROR DERIV';els.conn.className='pill off';els.reason.textContent='No se pudo abrir el canal público de Deriv. Revise Internet y vuelva a intentar.'};S.ws.onmessage=e=>handle(JSON.parse(e.data))}
function handle(d){if(d.error){els.reason.textContent=d.error.message;return}if(d.msg_type==='active_symbols'){const list=(d.active_symbols||[]).filter(x=>/boom|crash/i.test(x.underlying_symbol_name||x.display_name||''));els.symbol.innerHTML='';list.forEach(x=>{let o=document.createElement('option');o.value=x.underlying_symbol||x.symbol;o.textContent=x.underlying_symbol_name||x.display_name||o.value;els.symbol.appendChild(o)});if(list.length){S.symbol=els.symbol.value;subscribe()}}if(d.msg_type==='history'&&d.history){S.prices=(d.history.prices||[]).map(Number);S.times=d.history.times||[];analyze()}if(d.msg_type==='tick'){S.prices.push(Number(d.tick.quote));S.times.push(d.tick.epoch);if(S.prices.length>600){S.prices.shift();S.times.shift()}analyze()}}
function subscribe(){if(!S.symbol)return;send({forget_all:'ticks'});S.prices=[];S.times=[];send({ticks_history:S.symbol,count:300,end:'latest',style:'ticks',req_id:2});send({ticks:S.symbol,subscribe:1,req_id:3});els.reason.textContent='Recopilando datos del mercado…'}
const avg=a=>a.reduce((s,v)=>s+v,0)/(a.length||1); const sd=a=>{let m=avg(a);return Math.sqrt(avg(a.map(v=>(v-m)**2)))};function ema(a,n){if(!a.length)return 0;let k=2/(n+1),v=a[0];for(let x of a.slice(1))v=x*k+v*(1-k);return v}
function analyze(){let p=S.prices,n=p.length;if(n<40){els.ticks.textContent=n;draw();return}let cur=p[n-1],r=p.slice(-40),fast=ema(r.slice(-15),8),slow=ema(r,21),mom=(cur-p[n-11]),vol=sd(r.slice(-25)),unit=vol||Math.abs(cur)*.00001||1;let score=(fast-slow)/unit*.22+mom/unit*.12;let conf=Math.min(92,Math.round(50+Math.abs(score)*18));let dir=score>.35?'ALZA ↑':score<-.35?'BAJA ↓':'NEUTRAL';let deltas=r.slice(1).map((v,i)=>v-r[i]),largest=Math.max(...deltas.map(Math.abs)),spikeRisk=Math.min(95,Math.round(20+Math.max(0,(largest/(unit||1)-1))*10+Math.min(35,Math.abs(score)*8)));let phase='ESPERAR',reason='Sin confirmación suficiente.',alert=null,entry=null,exit=null;if(dir!=='NEUTRAL'&&conf>=62){phase='🟡 ALERTA';alert=cur;reason='Dirección emergente detectada. Vigilando confirmación.'}if(dir!=='NEUTRAL'&&conf>=72){phase='🟢 ENTRADA';entry=cur;alert=S.signal?.alert??cur;exit=cur+(dir.startsWith('ALZA')?1:-1)*unit*2.2;reason='Momentum y estructura confirman la dirección.'}S.signal={dir,conf,phase,alert,entry,exit,spikeRisk};els.price.textContent=cur.toFixed(5);els.ticks.textContent=n;els.direction.textContent=dir;els.confidence.textContent=conf+'%';els.phase.textContent=phase;els.reason.textContent=reason;els.alert.textContent=alert?.toFixed(5)||'—';els.entry.textContent=entry?.toFixed(5)||'—';els.exit.textContent=exit?.toFixed(5)||'—';els.spike.textContent=spikeRisk+'%';els.ind.innerHTML=`Momentum: ${mom.toFixed(5)}<br>Volatilidad: ${vol.toFixed(5)}<br>EMA rápida/lenta: ${fast.toFixed(5)} / ${slow.toFixed(5)}`;let key=phase+dir;if((phase.includes('ALERTA')||phase.includes('ENTRADA'))&&key!==S.lastLogged){S.lastLogged=key;logSignal();speak(`${phase.includes('ENTRADA')?'Entrada confirmada':'Alerta'} ${dir.startsWith('ALZA')?'al alza':'a la baja'} en ${els.symbol.options[els.symbol.selectedIndex]?.text||S.symbol}`)}draw()}
function logSignal(){let s=S.signal,tr=document.createElement('tr');tr.innerHTML=`<td>${new Date().toLocaleTimeString()}</td><td>${els.symbol.options[els.symbol.selectedIndex]?.text||S.symbol}</td><td>${s.dir}</td><td>${s.phase}</td><td>${s.conf}%</td><td>${s.alert?.toFixed(5)||'—'}</td><td>${s.entry?.toFixed(5)||'—'}</td><td>${s.exit?.toFixed(5)||'—'}</td>`;els.history.prepend(tr);while(els.history.children.length>30)els.history.lastChild.remove()}
function draw(){let c=els.chart,ctx=c.getContext('2d'),p=S.prices.slice(-160);ctx.clearRect(0,0,c.width,c.height);if(p.length<2)return;let min=Math.min(...p),max=Math.max(...p),pad=(max-min)*.15||1;min-=pad;max+=pad;let X=i=>i/(p.length-1)*(c.width-50)+25,Y=v=>c.height-25-(v-min)/(max-min)*(c.height-50);ctx.strokeStyle='#5bc0ff';ctx.lineWidth=2;ctx.beginPath();p.forEach((v,i)=>i?ctx.lineTo(X(i),Y(v)):ctx.moveTo(X(i),Y(v)));ctx.stroke();let s=S.signal||{};[[s.alert,'#ffd54a','ALERTA'],[s.entry,'#43e58f','ENTRADA'],[s.exit,'#ff6476','SALIDA']].forEach(([v,col,label])=>{if(v==null)return;let y=Y(v);ctx.strokeStyle=col;ctx.setLineDash([9,7]);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=col;ctx.font='bold 18px sans-serif';ctx.fillText(label+' '+Number(v).toFixed(5),18,Math.max(20,y-7))})}
els.connect.onclick=connect;els.symbol.onchange=()=>{S.symbol=els.symbol.value;S.signal=null;S.lastLogged='';subscribe()};$('voice').onclick=()=>{S.voice=!S.voice;$('voice').textContent=`🔊 Voz: ${S.voice?'ON':'OFF'}`};$('clear').onclick=()=>{S.signal=null;S.lastLogged='';draw()};window.addEventListener('resize',draw);
